Fix webpack link;
fengari-lua/fengari.io pull request #12
Opened 2018-06-06 04:18 UTC by bjornbytes

Fixes a link that was using markdown syntax.

2018-06-06 09:07 UTC, daurnimator requested changes
Could you prefix your commit message with the file changed?

2018-06-06 09:07 UTC, daurnimator commented on views/index.etlua
> +                <li><a href="https://github.com/fengari-lua/fengari-loader">fengari-loader</a>: to bundle lua code as part of a <a href="https://webpack.js.org">webpack</a> build process</li>
Minor nit: dropped the trailing `/` in the link.

2018-06-07 13:07 UTC, daurnimator approved these changes

2018-06-07 13:08 UTC, daurnimator commented
Thanks! Looks good to merge.

@giann I'm not at home for the next few weeks; could you merge + deploy?

2019-01-07 02:05 UTC, closed without merging

2019-01-07 02:59 UTC, daurnimator commented
@bjornbytes why did you close?

2019-01-07 03:23 UTC, bjornbytes commented
I was doing some github housekeeping.  I don't mind resubmitting this if you want, given it's a single link change it might be quicker for you to commit directly to master though.

2019-01-07 03:28 UTC, daurnimator commented
Rebased+merged onto master now.

2019-01-07 06:24 UTC, giann commented
Deployed